# Generated by Django 4.0.3 on 2022-04-24 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0003_alter_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vertenarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Middle_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=10)),
                ('College', models.CharField(max_length=50)),
                ('Experience', models.TextField(max_length=200)),
                ('Certificate_Copy', models.FileField(default='', max_length=4, upload_to='')),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customer')),
            ],
        ),
    ]
