# Generated by Django 2.0 on 2022-04-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agronomist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Middle_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('Phone', models.IntegerField(max_length=10)),
                ('College', models.CharField(max_length=50)),
                ('Experience', models.TextField(max_length=200)),
                ('Certificate_Copy', models.FileField(upload_to='')),
            ],
        ),
    ]
