# Generated by Django 4.0.3 on 2022-04-22 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agronomist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agronomist',
            name='Phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='agronomist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Upload_Photo', models.FileField(upload_to='')),
                ('Price', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=10)),
                ('agronomist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agronomist.agronomist')),
            ],
        ),
    ]
