# Generated by Django 4.0.3 on 2022-04-22 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_alter_customer_phone_alter_customer_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agroengineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Middle_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=10)),
                ('College', models.CharField(max_length=50)),
                ('Experience', models.TextField(max_length=200)),
                ('Certificate_Copy', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=300)),
                ('Last_Name', models.CharField(max_length=300)),
                ('Upload_Photo', models.FileField(upload_to='')),
                ('Price', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=10)),
                ('agroengineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
