# Generated by Django 4.0.3 on 2022-04-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agroengineer', '0002_rename_agroengineer_customer_agroengineer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agroengineer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
