# Generated by Django 4.0.3 on 2022-04-24 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_id'),
        ('Agroengineer', '0003_alter_agroengineer_id_alter_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agroengineer',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customer'),
        ),
        migrations.DeleteModel(
            name='customer',
        ),
    ]
